package org.example;


public class User {
    private int userID;
    private String username;
    private String hashedPassword;
    private String email;
    private String createdAt;

    // Constructor for creating a new User instance (for retrieval from the database)
    public User(int userID, String username, String hashedPassword, String email, String createdAt) {
        this.userID = userID;
        this.username = username;
        this.hashedPassword = hashedPassword;
        this.email = email;
        this.createdAt = createdAt;
    }

    // Constructor for adding a new user (without userID and createdAt, as those may be generated by the database)
    public User(String username, String hashedPassword, String email) {
        this.username = username;
        this.hashedPassword = hashedPassword;
        this.email = email;
    }

    // Getters
    public int getUserID() { return userID; }
    public String getUsername() { return username; }
    public String getHashedPassword() { return hashedPassword; }
    public String getEmail() { return email; }
    public String getCreatedAt() { return createdAt; }
}
